### PR TITLE
Check for write permissions before erroring out

### LINKED ISSUE #4: Patch out pacman's own check for root privileges

### PR DESCRIPTION
**Pull request by carstene1ns**
Fixes #4.

### CODE REVIEW

**Comment by sharkwouter** [comment]
Oh, this is nice. If this works, upstream might like to have it. I'll test it.

**Comment by carstene1ns** [comment]
> upstream might like to have it

Very unlikely. We can do this, because we always have write access to whole toolchain dir or nowhere inside.
This breaks horribly as soon as the database/cache/… is not writable.

**Comment by sharkwouter** [comment]
It seems installing without sudo doesn't work anymore. It asks for sudo permission during installation and then it fails the rest of the installation because of that. I have the log here: https://gist.github.com/sharkwouter/93d9be35e0dc3926b0e08095d22c965d

It seems this part of the patch doesn't have the intended effect: https://github.com/pspdev/psp-pacman/blob/c96418c4b71bc1d9bfcbf95cd8685d0248c31be9/patches/pacman-5.2.1.patch#L9

**Comment by carstene1ns** [comment]
This part is straight from the original patch to not install the bash-completion files in global (`/usr`) directory, but it needs bash-completion 2.10.
Can you check which version is installed?

**Pull request merged**
